<?php
/** 
* cache.module.php
*
* @package    shuguangCMS
* @author     shuguang QQ:5565907 <web@sgcms.cn>
* @copyright  Copyright (c) 2008-2010  (http://www.sgcms.cn)
* @license    http://www.sgcms.cn/license.txt
   
*/

if (!defined('SHUGUANGCMS')) exit();

return array (
  0 => 
  array (
    'id' => '4',
    'module_title' => '导航管理',
    'module_name' => 'Menu',
    'module_permission' => '浏览=Menu_index|录入=Menu_insert|编辑=Menu_modify|批量操作=Menu_command',
    'system_module' => '1',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  1 => 
  array (
    'id' => '7',
    'module_title' => '类别管理',
    'module_name' => 'Category',
    'module_permission' => '浏览=Category_index|编辑=Category_modify|批量操作=Category_update',
    'system_module' => '1',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  2 => 
  array (
    'id' => '8',
    'module_title' => '新闻管理',
    'module_name' => 'News',
    'module_permission' => '浏览=News_index|编辑=News_modify|录入=News_insert|移动栏目=News_move|批量操作=News_command',
    'system_module' => '1',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  3 => 
  array (
    'id' => '9',
    'module_title' => '产品管理',
    'module_name' => 'Product',
    'module_permission' => '浏览=Product_index|录入=Product_insert|编辑=Product_modify|批量操作=Product_command|订单管理=Product_order|移动类别=Product_move',
    'system_module' => '0',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  4 => 
  array (
    'id' => '10',
    'module_title' => '下载管理',
    'module_name' => 'Download',
    'module_permission' => '浏览=Download_index|录入=Download_insert|编辑=Download_modify|批量操作=Download_command|移动栏目=Download_move',
    'system_module' => '0',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  5 => 
  array (
    'id' => '11',
    'module_title' => '留言管理',
    'module_name' => 'Feedback',
    'module_permission' => '浏览=Feedback_index|录入=Feedback_insert|编辑=Feedback_modify|批量操作=Feedback_command',
    'system_module' => '0',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  6 => 
  array (
    'id' => '12',
    'module_title' => '招聘管理',
    'module_name' => 'Job',
    'module_permission' => '浏览=Job_index|录入=Job_insert|编辑=Job_modify|应聘管理=Job_resume|批量操作=Job_command',
    'system_module' => '0',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  7 => 
  array (
    'id' => '13',
    'module_title' => '公告管理',
    'module_name' => 'Notice',
    'module_permission' => '浏览=Notice_index|录入=Notice_insert|编辑=Notice_modify|批量操作=Notice_command',
    'system_module' => '0',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  8 => 
  array (
    'id' => '14',
    'module_title' => '链接管理',
    'module_name' => 'Link',
    'module_permission' => '浏览=Link_index|录入=Link_insert|编辑=Link_modify|批量操作=Link_command',
    'system_module' => '0',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  9 => 
  array (
    'id' => '15',
    'module_title' => '单页管理',
    'module_name' => 'Page',
    'module_permission' => '浏览=Page_index|录入=Page_insert|编辑=Page_modify|批量操作=Page_command',
    'system_module' => '1',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  10 => 
  array (
    'id' => '16',
    'module_title' => '广告管理',
    'module_name' => 'Ad',
    'module_permission' => '浏览=Ad_index|录入=Ad_insert|编辑=Ad_modify|批量操作=Ad_command',
    'system_module' => '0',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  11 => 
  array (
    'id' => '27',
    'module_title' => 'Tags',
    'module_name' => 'Tags',
    'module_permission' => '管理=Tags',
    'system_module' => '1',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  12 => 
  array (
    'id' => '28',
    'module_title' => '评论管理',
    'module_name' => 'Comment',
    'module_permission' => '浏览=Comment_index|回复=Comment_modify|批量操作=Comment_command',
    'system_module' => '0',
    'left_menu' => '1',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  13 => 
  array (
    'id' => '29',
    'module_title' => '管理员管理',
    'module_name' => 'Admin',
    'module_permission' => '浏览=Admin_index|录入=Admin_insert|编辑=Admin_modify|批量操作=Admin_command',
    'system_module' => '1',
    'left_menu' => '0',
    'developer' => '',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  14 => 
  array (
    'id' => '31',
    'module_title' => '模板风格',
    'module_name' => 'Theme',
    'module_permission' => '管理=Theme',
    'system_module' => '1',
    'left_menu' => '0',
    'developer' => 'developer:shuguangcms
web:http://www.sgcms.cn',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  15 => 
  array (
    'id' => '30',
    'module_title' => '角色管理',
    'module_name' => 'AdminRole',
    'module_permission' => '浏览=AdminRole_index|录入=AdminRole_insert|编辑=AdminRole_modify|批量操作=AdminRole_command',
    'system_module' => '1',
    'left_menu' => '0',
    'developer' => 'developer:shuguangcms
web:http://www.sgcms.cn',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  16 => 
  array (
    'id' => '32',
    'module_title' => '模块管理',
    'module_name' => 'Module',
    'module_permission' => '浏览=Module_index|编辑=Module_modify|安装=Module_install|卸载=Module_uninstall',
    'system_module' => '1',
    'left_menu' => '0',
    'developer' => 'developer:shuguangcms
web:http://www.sgcms.cn',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  17 => 
  array (
    'id' => '33',
    'module_title' => '系统配置',
    'module_name' => 'Config',
    'module_permission' => '浏览系统配置=Config_index|编辑系统配置=Config_modify|浏览核心配置=Config_core|编辑核心配置=Config_coreModify',
    'system_module' => '1',
    'left_menu' => '0',
    'developer' => 'developer:shuguangcms
web:http://www.sgcms.cn',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  18 => 
  array (
    'id' => '34',
    'module_title' => '数据库管理',
    'module_name' => 'Database',
    'module_permission' => '浏览=Database_index|执行SQL=Database_query|备份数据库=Database_export|恢复数据库=Database_import',
    'system_module' => '1',
    'left_menu' => '0',
    'developer' => 'developer:shuguangcms
web:http://www.sgcms.cn',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  19 => 
  array (
    'id' => '35',
    'module_title' => '操作日志管理',
    'module_name' => 'AdminLog',
    'module_permission' => '管理=AdminLog',
    'system_module' => '1',
    'left_menu' => '0',
    'developer' => 'developer:shuguangcms
web:http://www.sgcms.cn',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  20 => 
  array (
    'id' => '36',
    'module_title' => '工具箱管理',
    'module_name' => 'Tools',
    'module_permission' => '管理=Tools',
    'system_module' => '1',
    'left_menu' => '0',
    'developer' => 'developer:shuguangcms
web:http://www.sgcms.cn',
    'build_version' => '2.0',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
  21 => 
  array (
    'id' => '37',
    'module_title' => '数据调用',
    'module_name' => 'Label',
    'module_permission' => '管理=Label',
    'system_module' => '1',
    'left_menu' => '0',
    'developer' => 'developer:shuguangcms',
    'build_version' => '',
    'display_order' => '0',
    'status' => '0',
    'create_time' => '0',
    'update_time' => '0',
  ),
);