<?php
/** 
* cache.category.php
*
* @package    shuguangCMS
* @author     shuguang QQ:5565907 <web@sgcms.cn>
* @copyright  Copyright (c) 2008-2010  (http://www.sgcms.cn)
* @license    http://www.sgcms.cn/license.txt
   
*/

if (!defined('SHUGUANGCMS')) exit();

return array (
  0 => 
  array (
    'id' => '1',
    'module' => 'News',
    'parent_id' => '0',
    'title' => '新闻模块',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262410906',
    'update_time' => '1262415121',
  ),
  1 => 
  array (
    'id' => '2',
    'module' => '',
    'parent_id' => '1',
    'title' => '行业新闻',
    'keyword' => '',
    'description' => '公司动态',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262410927',
    'update_time' => '1272609561',
  ),
  2 => 
  array (
    'id' => '3',
    'module' => '',
    'parent_id' => '1',
    'title' => '加盟动态',
    'keyword' => '',
    'description' => '行业动态',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262410939',
    'update_time' => '1272609543',
  ),
  3 => 
  array (
    'id' => '4',
    'module' => '',
    'parent_id' => '1',
    'title' => '市场活动',
    'keyword' => '',
    'description' => '市场信息',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262410963',
    'update_time' => '1272609523',
  ),
  4 => 
  array (
    'id' => '5',
    'module' => '',
    'parent_id' => '1',
    'title' => '集团新闻',
    'keyword' => '',
    'description' => '政策信息',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262410987',
    'update_time' => '1272609495',
  ),
  5 => 
  array (
    'id' => '6',
    'module' => 'Product',
    'parent_id' => '0',
    'title' => '早教商城',
    'keyword' => '',
    'description' => '产品模块',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262410998',
    'update_time' => '1272594287',
  ),
  6 => 
  array (
    'id' => '7',
    'module' => '',
    'parent_id' => '6',
    'title' => '蒙氏教具',
    'keyword' => '',
    'description' => '新品上市',
    'display_order' => '2',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411013',
    'update_time' => '1272594330',
  ),
  7 => 
  array (
    'id' => '8',
    'module' => '',
    'parent_id' => '6',
    'title' => '文化类产品',
    'keyword' => '',
    'description' => '文化类产品',
    'display_order' => '0',
    'protected' => '0',
    'status' => '1',
    'create_time' => '1262411055',
    'update_time' => '0',
  ),
  8 => 
  array (
    'id' => '9',
    'module' => '',
    'parent_id' => '6',
    'title' => '蒙氏玩具',
    'keyword' => '',
    'description' => '休闲类产品',
    'display_order' => '1',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411067',
    'update_time' => '1272594357',
  ),
  9 => 
  array (
    'id' => '10',
    'module' => '',
    'parent_id' => '6',
    'title' => '体育类产品',
    'keyword' => '',
    'description' => '体育类产品',
    'display_order' => '0',
    'protected' => '0',
    'status' => '1',
    'create_time' => '1262411092',
    'update_time' => '0',
  ),
  10 => 
  array (
    'id' => '11',
    'module' => '',
    'parent_id' => '10',
    'title' => '球类',
    'keyword' => '',
    'description' => '球类',
    'display_order' => '0',
    'protected' => '0',
    'status' => '1',
    'create_time' => '1262411108',
    'update_time' => '0',
  ),
  11 => 
  array (
    'id' => '12',
    'module' => '',
    'parent_id' => '10',
    'title' => '服饰类',
    'keyword' => '',
    'description' => '服饰类',
    'display_order' => '0',
    'protected' => '0',
    'status' => '1',
    'create_time' => '1262411122',
    'update_time' => '0',
  ),
  12 => 
  array (
    'id' => '13',
    'module' => '',
    'parent_id' => '6',
    'title' => '早教资料',
    'keyword' => '',
    'description' => '自行车',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411152',
    'update_time' => '1272594398',
  ),
  13 => 
  array (
    'id' => '14',
    'module' => 'Download',
    'parent_id' => '0',
    'title' => '下载模块',
    'keyword' => '',
    'description' => '下载模块',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411171',
    'update_time' => '1267110782',
  ),
  14 => 
  array (
    'id' => '15',
    'module' => '',
    'parent_id' => '14',
    'title' => '系统软件',
    'keyword' => '',
    'description' => '系统软件',
    'display_order' => '1',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411182',
    'update_time' => '1262411190',
  ),
  15 => 
  array (
    'id' => '16',
    'module' => '',
    'parent_id' => '14',
    'title' => '办公软件',
    'keyword' => '',
    'description' => '办公软件',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411204',
    'update_time' => '0',
  ),
  16 => 
  array (
    'id' => '17',
    'module' => '',
    'parent_id' => '14',
    'title' => '恢复类软件',
    'keyword' => '',
    'description' => '恢复类软件',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1262411216',
    'update_time' => '0',
  ),
  17 => 
  array (
    'id' => '33',
    'module' => '',
    'parent_id' => '32',
    'title' => '首页横幅',
    'keyword' => '',
    'description' => '首页横幅',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267112629',
    'update_time' => '1267288982',
  ),
  18 => 
  array (
    'id' => '32',
    'module' => 'Ad',
    'parent_id' => '0',
    'title' => '广告模块',
    'keyword' => '',
    'description' => '广告模块',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267112377',
    'update_time' => '1267112406',
  ),
  19 => 
  array (
    'id' => '34',
    'module' => '',
    'parent_id' => '32',
    'title' => '公共',
    'keyword' => '',
    'description' => '公共',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267112648',
    'update_time' => '0',
  ),
  20 => 
  array (
    'id' => '35',
    'module' => 'Link',
    'parent_id' => '0',
    'title' => '链接类型',
    'keyword' => '',
    'description' => '链接类型',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267287014',
    'update_time' => '0',
  ),
  21 => 
  array (
    'id' => '36',
    'module' => '',
    'parent_id' => '35',
    'title' => '默认类型',
    'keyword' => '',
    'description' => '普通链接',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1267287066',
    'update_time' => '1267288647',
  ),
  22 => 
  array (
    'id' => '39',
    'module' => 'News',
    'parent_id' => '0',
    'title' => '育儿宝典',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1272593534',
    'update_time' => '0',
  ),
  23 => 
  array (
    'id' => '40',
    'module' => 'Page',
    'parent_id' => '0',
    'title' => '中心简介',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1272593928',
    'update_time' => '0',
  ),
  24 => 
  array (
    'id' => '41',
    'module' => '',
    'parent_id' => '40',
    'title' => '品牌定位',
    'keyword' => '',
    'description' => '',
    'display_order' => '0',
    'protected' => '0',
    'status' => '0',
    'create_time' => '1272594078',
    'update_time' => '0',
  ),
);